inherit_from: .rubocop_todo.yml

# Don't require new lines between one-liner methods
Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# We sometimes need Java method names for interoperability
# Like java calling our methods like `controlResized`
Style/MethodName:
  Enabled: false

# We don't care if we do kind_of? or is_a?
Style/ClassCheck:
  Enabled: false

# Don't ever try to take my `inject` from me, reduce is ok too
Style/CollectionMethods:
  PreferredMethods:
    inject: 'inject'

# We don't have a strong opinion on how you use spaces inside braces
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# We like to be flexible if we want to add in interpolation
# see discussion #859
Style/StringLiterals:
  Enabled: false

# We like the flexibility of adding additional items to the hash
# see discussion in #859
Style/TrailingComma:
  Enabled: false

# We have several places where, because of instance scoping in apps,
# we don't want to use attr_reader. (Also misattributes on predicate
# methods)
Style/TrivialAccessors:
  Enabled: false

# We don't care if you use %w or literal string arrays
Style/WordArray:
  Enabled: false
